FROM ubuntu:utopic
MAINTAINER Pasi Lammi <pasi.lammi@iki.fi>

RUN apt-get -y update
RUN apt-get -f -y upgrade
RUN apt-get -y install cmake libpng-dev libjpeg-dev libxxf86vm1 libxxf86vm-dev libxi-dev libxrandr-dev git build-essential wget doxygen ghostscript libqtgui4 libglpk-dev libiomp-dev python-cvxopt python-dev unzip
